Repository Quansight-Labs/free-threaded-compatibility, pull requests merged in 2024-11, with the labels that each got.

#102 Add list with more resource on free-threading & CPython internals
  .pre-commit-config.yaml
  docs/resources.md
  mkdocs.yml
Labels: documentation

#106 clarify limited API support a bit
  docs/porting.md
Labels: documentation

#105 Document jupyter notebook status and how to install a jupyter kernel
  docs/installing_cpython.md
  docs/tracking.md
Labels: documentation

#109 Update TOC on index page, make headers uniform
  docs/debugging.md
  docs/index.md
  docs/installing_cpython.md
  docs/resources.md
  docs/running-gil-disabled.md
  docs/tracking.md
Labels: documentation

#110 link to hugovk's tracker in the tracking page
  docs/tracking.md
Labels: documentation

#108 Detail a list of available pytest plugins to perform parallel exploration
  docs/debugging.md
Labels: documentation

#113 Update tracker for Bazel, SciPy, Pandas plus add blog post link
  docs/resources.md
  docs/tracking.md
Labels: documentation, status tracker update

#114 doc: add unittest-ft to the docs on testing
  docs/porting.md
Labels: documentation

#115 Add rust to porting guide and update tracking guide
  docs/porting.md
  docs/tracking.md
Labels: documentation

#119 add bcrypt, kiwisolver, and maturin to tracking table
  docs/tracking.md
Labels: status tracker update
