Repository Quansight-Labs/free-threaded-compatibility, pull requests merged in 2025-04, with the labels that each got.

#162 add pycares and pynacl to the tracking table
  docs/tracking.md
Labels: status tracker update

#164 tracker update: h5py, nox, pydantic, setuptools-rust
  docs/tracking.md
Labels: status tracker update

#166 docs: add a contribution guide
  CONTRIBUTING.md
  docs/contributing.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#170 Update tracking table with aio-libs and brotli
  docs/tracking.md
Labels: status tracker update

#173 update tracking table for SWIG support
  docs/tracking.md
Labels: status tracker update

#172 Reorder topics in README and light editing of content
  docs/index.md
Labels: documentation, maintenance

#184 Add PyYAML-ft and setproctitle to tracking table
  docs/tracking.md
Labels: status tracker update
