Repository Quansight-Labs/free-threaded-compatibility, pull requests merged in 2025-02, with the labels that each got.

#135 add cramjam, kornia-rs, libcst, rust-numpy, safetensors, and swig to tracking table
  docs/tracking.md
Labels: status tracker update

#137 Upgrade CI jobs and pre-commit hooks
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  docs/ci.md
  docs/debugging.md
  docs/installing_cpython.md
  docs/porting.md
  docs/running-gil-disabled.md
  docs/tracking.md
Labels: maintenance

#138 add docs on running pytest under TSAN
  docs/debugging.md
Labels: documentation

#140 TSAN debugging improvements
  docs/debugging.md
Labels: documentation
